/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/skullMask.glb 
Author: Doink (https://sketchfab.com/Doinkoloink)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hannya-mask-skull-efbce7b42cc14f389cb8b209eba0b6eb
Title: Hannya mask skull
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function SkullMask(props) {
  const { nodes, materials } = useGLTF('models/skullMask.glb')


  const group = useRef(); // Ref for the group containing the helmet mesh
  useFrame(() => {
    if (group.current) {
      group.current.rotation.y += 0.008; // Adjust the rotation speed as needed
    }
  });


  return (
    <group {...props} dispose={null} ref={group}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.lambert1} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.lambert1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/skullMask.glb')
